# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'NHAVEditor.xcworkspace'

project 'NHAVEditorDemo/NHAVEditorDemo'

target 'NHAVEditorDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Toast-Swift'
  pod 'IBAnimatable'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Moya'
  pod 'ObjectMapper'
  pod 'Realm'
  pod "Codextended"


  target 'NHAVEditorDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
